#!/bin/bash

# 00_test.txt
echo -n -e "abcdefg\nhijklmnop\nqrs" > 00_test.txt

# 01_empty.txt
touch 01_empty.txt

# 02_empty_dir
mkdir 02_empty_dir

# 03_dir
mkdir 03_dir
echo -n -e "asdfjalskdj\nalsdkjfl;aksd\nla;sdkjfiowelfj\npao;ejflkmv" > 03_dir/file.txt
mkdir 03_dir/directory
echo -n -e "alkdjfl;\na;ldfjad" > 03_dir/directory/file.txt

# 04_large.bin
head -c 2048 /dev/urandom > 04_large.bin

# 05_link.txt
ln -s 00_test.txt 05_link.txt

# 06_link_dne
ln -s dne 06_link_dne

# 07_link_recursive
ln -s 07_link_recursive 07_link_recursive

# 08_long_filename
echo -n -e "abc\ndef\nghi" > 08_really_long_name_really_long_name_really_long_name_really_long_name_really_long_name_really_long_name.txt

# 09_long_dir
mkdir 09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir
mkdir 09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir/09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really
echo -n -e "adsjfakl;sdj\n;lkajdf;lkajsif\n" > 09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir/file.txt
echo -n -e "abcd\nefghij\nklmn" > 09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir/09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really/file.txt

# 10_ro.txt
echo -n -e "read-only!" > 10_ro.txt
chmod 400 10_ro.txt

# 11_no_read
mkdir 11_no_read
mkdir 11_no_read/can_read
mkdir 11_no_read/cant_read

echo -n -e "cant read!" > 11_no_read/noread.txt
echo -n -e "stuff" > 11_no_read/can_read/stuff.txt
echo -n -e "more stuff" > 11_no_read/cant_read/stuff.txt

chmod 000 11_no_read/noread.txt
chmod 000 11_no_read/cant_read

# 12_all
mkdir 12_all
cp 00_test.txt 12_all/test.txt
cp 01_empty.txt 12_all/empty.txt
cp -r 02_empty_dir 12_all/empty_dir
cp -r 03_dir 12_all/dir
cp 04_large.bin 12_all/large.bin
ln -s 12_all/test.txt 12_all/link.txt
ln -s dne 12_all/link_dne
ln -s 12_all/link_recursive 12_all/link_recursive
cp 08_really_long_name_really_long_name_really_long_name_really_long_name_really_long_name_really_long_name.txt 12_all/really_long_name_really_long_name_really_long_name_really_long_name_really_long_name_really_long_name.txt
cp -r 09_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir 12_all/really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir_really_long_dir
echo -n -e "read-only!" > 12_all/ro.txt
chmod 400 12_all/ro.txt
echo -n -e "write-only!" > 12_all/wo.txt
chmod 200 12_all/wo.txt
