#!/bin/bash

MYTAR_LOC="$( pwd )/.."

./gen_expected

if [ ! -d "outputs" ]; then
	mkdir outputs
fi

pushd ../
make
popd

for file in inputs/*; do
   echo "Testing with ${file}"

   BASE=`basename ${file}`

   echo -n "    Create -- "

   cd inputs
   valgrind -q --error-exitcode=2 --leak-check=full --log-file=../outputs/${BASE}_cv.valg ${MYTAR_LOC}/mytar cvf ../outputs/${BASE}.tar ${BASE} > ../outputs/${BASE}_cv.log 2>&1
   vg=$?
   cd ..

   if [ $vg -eq 0 ]; then

      rm outputs/${BASE}_cv.valg
      
      diff outputs/${BASE}.tar expected/${BASE}.tar &> outputs/${BASE}_cv.diff && diff expected/${BASE}_cv.log outputs/${BASE}_cv.log &> outputs/${BASE}_cv.log.diff

      if [ $? -eq 0 ]; then
         echo "Succeeded"

         rm outputs/${BASE}_cv.diff
         rm outputs/${BASE}_cv.log
         rm outputs/${BASE}_cv.log.diff
      else
         echo "Failed"
         echo "        See differences in outputs/${BASE}_cv.diff and outputs/${BASE}_cv.log.diff"
      fi
   elif [ $vg -eq 2 ]; then
      echo "Failed"
      echo "        Valgrind error"
   else
      echo "Failed"
      echo "        Runtime error"
   fi
      

   echo -n "    List   -- "

   # program testing
   valgrind -q --error-exitcode=2 --leak-check=full --log-file=outputs/${BASE}_t.valg ${MYTAR_LOC}/mytar tf outputs/${BASE}.tar > outputs/${BASE}_t.log 2>&1
   vg=$?

   if [ $vg -eq 0 ]; then

      rm outputs/${BASE}_t.valg

      # compare results
      diff outputs/${BASE}_t.log expected/${BASE}_t.log &> outputs/${BASE}_t.diff

      if [ $? -eq 0 ]; then
         echo "Succeeded"

         # comment out these lines to retain output and diff files
         rm outputs/${BASE}_t.diff
         rm outputs/${BASE}_t.log
      else
         echo "Failed"
         echo "        See differences in outputs/${BASE}_t.diff"
      fi
   elif [ $vg -eq 2 ]; then
      echo "Failed"
      echo "        Valgrind error"
   else
      echo "Failed"
      echo "        Runtime error"
   fi

   echo -n "    V List -- "

   valgrind -q --error-exitcode=2 --leak-check=full --log-file=outputs/${BASE}_tv.valg ${MYTAR_LOC}/mytar tvf outputs/${BASE}.tar > outputs/${BASE}_tv.log 2>&1
   vg=$?

   if [ $vg -eq 0 ]; then

      rm outputs/${BASE}_tv.valg

      diff outputs/${BASE}_tv.log expected/${BASE}_tv.log &> outputs/${BASE}_tv.diff

      if [ $? -eq 0 ]; then
         echo "Succeeded"

         rm outputs/${BASE}_tv.diff
         rm outputs/${BASE}_tv.log
      else
         echo "Failed"
         echo "        See differences in outputs/${BASE}_tv.diff"
      fi
   elif [ $vg -eq 2 ]; then
      echo "Failed"
      echo "        Valgrind error"
   else
      echo "Failed"
      echo "        Runtime error"
   fi

   echo -n "    Extract-- "

   cd outputs
   valgrind -q --error-exitcode=2 --leak-check=full --log-file=${BASE}_xv.valg ${MYTAR_LOC}/mytar xvf ${BASE}.tar > ${BASE}_xv.log 2>&1
   vg=$?
   cd ..

   if [ $vg -eq 0 ]; then

      rm outputs/${BASE}_xv.valg

      diff outputs/${BASE}_xv.log expected/${BASE}_xv.log &> outputs/${BASE}_xv.diff && diff -r --no-dereference outputs/${BASE} ${file} &> outputs/${BASE}_x.diff

      if [ $? -eq 0 ]; then
         echo "Succeeded"

         rm outputs/${BASE}_xv.diff
         rm outputs/${BASE}_x.diff
         rm outputs/${BASE}_xv.log
         rm outputs/${BASE}.tar
         rm -r outputs/${BASE}
      else
         echo "Failed"
         echo "        See differences in outputs/${BASE}_xv.diff and outputs/${BASE}_x.diff"
      fi
   elif [ $vg -eq 2 ]; then
      echo "Failed"
      echo "        Valgrind error"
   else
      echo "Failed"
      echo "        Runtime error"
   fi


done
